# Make Ctrl + Space my Prefix (trigger) key
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'dracula/tmux'

# Dracula Config
# set -g @dracula-show-powerline true
# set -g @dracula-show-flags true
# set -g @dracula-show-left-icon session
set -g status-position top
set -g status-style "bg=#1362B2,fg=white"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Ensure window index numbers get reordered on delete
set-option -g renumber-windows on

# Make it scrollable
setw -g mouse on

# Initialize TPM (keep this at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
